version: '3.9'
services:
  local-dynamo-service:
    image: zestyco/dynamodb-challenge:amd
    ports:
      - "8000:8000"
  go-app:
    build: 
      context: .
      dockerfile: app/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - "local-dynamo-service"